# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c277f180199448e47317f9992b7db4618b1477c3763e79ed47680fca8ff9e998831a8b37bb7be6f7fff34636922ada9d87b40971c3f7e20489b7af23de5eb858

test:
  secret_key_base: c7fcabb4cb62326a7880c33f7b73d68b6a476da880c953b78bda8fe90216bc31b292fa345de0e70fdc54913f27c43cf95a569359d27eeebcb005111b6bd5f1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
